// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

// Protobuf Java Version: 3.25.1
package land.gno.gnomobile.v1;

public final class Rpc {
  private Rpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * <pre>
   * The ErrCode enum defines errors for gRPC API functions. These are converted
   * from the Go error types returned by gnoclient.
   * </pre>
   *
   * Protobuf enum {@code land.gno.gnomobile.v1.ErrCode}
   */
  public enum ErrCode
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <pre>
     * Undefined is the default value. It should never be set manually
     * </pre>
     *
     * <code>Undefined = 0;</code>
     */
    Undefined(0),
    /**
     * <pre>
     * TODO indicates that you plan to create an error later
     * </pre>
     *
     * <code>TODO = 1;</code>
     */
    TODO(1),
    /**
     * <pre>
     * ErrNotImplemented indicates that a method is not implemented yet
     * </pre>
     *
     * <code>ErrNotImplemented = 2;</code>
     */
    ErrNotImplemented(2),
    /**
     * <pre>
     * ErrInternal indicates an unknown error (without Code), i.e. in gRPC
     * </pre>
     *
     * <code>ErrInternal = 3;</code>
     */
    ErrInternal(3),
    /**
     * <code>ErrInvalidInput = 100;</code>
     */
    ErrInvalidInput(100),
    /**
     * <code>ErrBridgeInterrupted = 101;</code>
     */
    ErrBridgeInterrupted(101),
    /**
     * <code>ErrMissingInput = 102;</code>
     */
    ErrMissingInput(102),
    /**
     * <code>ErrSerialization = 103;</code>
     */
    ErrSerialization(103),
    /**
     * <code>ErrDeserialization = 104;</code>
     */
    ErrDeserialization(104),
    /**
     * <code>ErrInitService = 105;</code>
     */
    ErrInitService(105),
    /**
     * <code>ErrCryptoKeyTypeUnknown = 150;</code>
     */
    ErrCryptoKeyTypeUnknown(150),
    /**
     * <pre>
     * ErrCryptoKeyNotFound indicates that the doesn't exist in the keybase
     * </pre>
     *
     * <code>ErrCryptoKeyNotFound = 151;</code>
     */
    ErrCryptoKeyNotFound(151),
    /**
     * <pre>
     * ErrNoActiveAccount indicates that no active account has been set with SelectAccount
     * </pre>
     *
     * <code>ErrNoActiveAccount = 152;</code>
     */
    ErrNoActiveAccount(152),
    /**
     * <code>ErrRunGRPCServer = 153;</code>
     */
    ErrRunGRPCServer(153),
    /**
     * <pre>
     * ErrDecryptionFailed indicates a decryption failure including a wrong password
     * </pre>
     *
     * <code>ErrDecryptionFailed = 154;</code>
     */
    ErrDecryptionFailed(154),
    /**
     * <code>ErrTxDecode = 200;</code>
     */
    ErrTxDecode(200),
    /**
     * <code>ErrInvalidSequence = 201;</code>
     */
    ErrInvalidSequence(201),
    /**
     * <code>ErrUnauthorized = 202;</code>
     */
    ErrUnauthorized(202),
    /**
     * <pre>
     * ErrInsufficientFunds indicates that there are insufficient funds to pay for fees
     * </pre>
     *
     * <code>ErrInsufficientFunds = 203;</code>
     */
    ErrInsufficientFunds(203),
    /**
     * <pre>
     * ErrUnknownRequest indicates that the path of a realm function call is unrecognized
     * </pre>
     *
     * <code>ErrUnknownRequest = 204;</code>
     */
    ErrUnknownRequest(204),
    /**
     * <pre>
     * ErrInvalidAddress indicates that an account address is blank or the bech32 can't be decoded
     * </pre>
     *
     * <code>ErrInvalidAddress = 205;</code>
     */
    ErrInvalidAddress(205),
    /**
     * <pre>
     * ErrUnknownAddress indicates that the address is unknown on the blockchain
     * </pre>
     *
     * <code>ErrUnknownAddress = 206;</code>
     */
    ErrUnknownAddress(206),
    /**
     * <pre>
     * ErrInvalidPubKey indicates that the public key was not found or has an invalid algorithm or format
     * </pre>
     *
     * <code>ErrInvalidPubKey = 207;</code>
     */
    ErrInvalidPubKey(207),
    /**
     * <pre>
     * ErrInsufficientCoins indicates that the transaction has insufficient account funds to send
     * </pre>
     *
     * <code>ErrInsufficientCoins = 208;</code>
     */
    ErrInsufficientCoins(208),
    /**
     * <pre>
     * ErrInvalidCoins indicates that the transaction Coins are not sorted, or don't have a
     * positive amount, or the coin Denom contains upper case characters
     * </pre>
     *
     * <code>ErrInvalidCoins = 209;</code>
     */
    ErrInvalidCoins(209),
    /**
     * <pre>
     * ErrInvalidGasWanted indicates that the transaction gas wanted is too large or otherwise invalid
     * </pre>
     *
     * <code>ErrInvalidGasWanted = 210;</code>
     */
    ErrInvalidGasWanted(210),
    /**
     * <pre>
     * ErrOutOfGas indicates that the transaction doesn't have enough gas
     * </pre>
     *
     * <code>ErrOutOfGas = 211;</code>
     */
    ErrOutOfGas(211),
    /**
     * <pre>
     * ErrMemoTooLarge indicates that the transaction memo is too large
     * </pre>
     *
     * <code>ErrMemoTooLarge = 212;</code>
     */
    ErrMemoTooLarge(212),
    /**
     * <pre>
     * ErrInsufficientFee indicates that the gas fee is insufficient
     * </pre>
     *
     * <code>ErrInsufficientFee = 213;</code>
     */
    ErrInsufficientFee(213),
    /**
     * <pre>
     * ErrTooManySignatures indicates that the transaction has too many signatures
     * </pre>
     *
     * <code>ErrTooManySignatures = 214;</code>
     */
    ErrTooManySignatures(214),
    /**
     * <pre>
     * ErrNoSignatures indicates that the transaction has no signatures
     * </pre>
     *
     * <code>ErrNoSignatures = 215;</code>
     */
    ErrNoSignatures(215),
    /**
     * <pre>
     * ErrGasOverflow that an action results in a gas consumption unsigned integer overflow
     * </pre>
     *
     * <code>ErrGasOverflow = 216;</code>
     */
    ErrGasOverflow(216),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * Undefined is the default value. It should never be set manually
     * </pre>
     *
     * <code>Undefined = 0;</code>
     */
    public static final int Undefined_VALUE = 0;
    /**
     * <pre>
     * TODO indicates that you plan to create an error later
     * </pre>
     *
     * <code>TODO = 1;</code>
     */
    public static final int TODO_VALUE = 1;
    /**
     * <pre>
     * ErrNotImplemented indicates that a method is not implemented yet
     * </pre>
     *
     * <code>ErrNotImplemented = 2;</code>
     */
    public static final int ErrNotImplemented_VALUE = 2;
    /**
     * <pre>
     * ErrInternal indicates an unknown error (without Code), i.e. in gRPC
     * </pre>
     *
     * <code>ErrInternal = 3;</code>
     */
    public static final int ErrInternal_VALUE = 3;
    /**
     * <code>ErrInvalidInput = 100;</code>
     */
    public static final int ErrInvalidInput_VALUE = 100;
    /**
     * <code>ErrBridgeInterrupted = 101;</code>
     */
    public static final int ErrBridgeInterrupted_VALUE = 101;
    /**
     * <code>ErrMissingInput = 102;</code>
     */
    public static final int ErrMissingInput_VALUE = 102;
    /**
     * <code>ErrSerialization = 103;</code>
     */
    public static final int ErrSerialization_VALUE = 103;
    /**
     * <code>ErrDeserialization = 104;</code>
     */
    public static final int ErrDeserialization_VALUE = 104;
    /**
     * <code>ErrInitService = 105;</code>
     */
    public static final int ErrInitService_VALUE = 105;
    /**
     * <code>ErrCryptoKeyTypeUnknown = 150;</code>
     */
    public static final int ErrCryptoKeyTypeUnknown_VALUE = 150;
    /**
     * <pre>
     * ErrCryptoKeyNotFound indicates that the doesn't exist in the keybase
     * </pre>
     *
     * <code>ErrCryptoKeyNotFound = 151;</code>
     */
    public static final int ErrCryptoKeyNotFound_VALUE = 151;
    /**
     * <pre>
     * ErrNoActiveAccount indicates that no active account has been set with SelectAccount
     * </pre>
     *
     * <code>ErrNoActiveAccount = 152;</code>
     */
    public static final int ErrNoActiveAccount_VALUE = 152;
    /**
     * <code>ErrRunGRPCServer = 153;</code>
     */
    public static final int ErrRunGRPCServer_VALUE = 153;
    /**
     * <pre>
     * ErrDecryptionFailed indicates a decryption failure including a wrong password
     * </pre>
     *
     * <code>ErrDecryptionFailed = 154;</code>
     */
    public static final int ErrDecryptionFailed_VALUE = 154;
    /**
     * <code>ErrTxDecode = 200;</code>
     */
    public static final int ErrTxDecode_VALUE = 200;
    /**
     * <code>ErrInvalidSequence = 201;</code>
     */
    public static final int ErrInvalidSequence_VALUE = 201;
    /**
     * <code>ErrUnauthorized = 202;</code>
     */
    public static final int ErrUnauthorized_VALUE = 202;
    /**
     * <pre>
     * ErrInsufficientFunds indicates that there are insufficient funds to pay for fees
     * </pre>
     *
     * <code>ErrInsufficientFunds = 203;</code>
     */
    public static final int ErrInsufficientFunds_VALUE = 203;
    /**
     * <pre>
     * ErrUnknownRequest indicates that the path of a realm function call is unrecognized
     * </pre>
     *
     * <code>ErrUnknownRequest = 204;</code>
     */
    public static final int ErrUnknownRequest_VALUE = 204;
    /**
     * <pre>
     * ErrInvalidAddress indicates that an account address is blank or the bech32 can't be decoded
     * </pre>
     *
     * <code>ErrInvalidAddress = 205;</code>
     */
    public static final int ErrInvalidAddress_VALUE = 205;
    /**
     * <pre>
     * ErrUnknownAddress indicates that the address is unknown on the blockchain
     * </pre>
     *
     * <code>ErrUnknownAddress = 206;</code>
     */
    public static final int ErrUnknownAddress_VALUE = 206;
    /**
     * <pre>
     * ErrInvalidPubKey indicates that the public key was not found or has an invalid algorithm or format
     * </pre>
     *
     * <code>ErrInvalidPubKey = 207;</code>
     */
    public static final int ErrInvalidPubKey_VALUE = 207;
    /**
     * <pre>
     * ErrInsufficientCoins indicates that the transaction has insufficient account funds to send
     * </pre>
     *
     * <code>ErrInsufficientCoins = 208;</code>
     */
    public static final int ErrInsufficientCoins_VALUE = 208;
    /**
     * <pre>
     * ErrInvalidCoins indicates that the transaction Coins are not sorted, or don't have a
     * positive amount, or the coin Denom contains upper case characters
     * </pre>
     *
     * <code>ErrInvalidCoins = 209;</code>
     */
    public static final int ErrInvalidCoins_VALUE = 209;
    /**
     * <pre>
     * ErrInvalidGasWanted indicates that the transaction gas wanted is too large or otherwise invalid
     * </pre>
     *
     * <code>ErrInvalidGasWanted = 210;</code>
     */
    public static final int ErrInvalidGasWanted_VALUE = 210;
    /**
     * <pre>
     * ErrOutOfGas indicates that the transaction doesn't have enough gas
     * </pre>
     *
     * <code>ErrOutOfGas = 211;</code>
     */
    public static final int ErrOutOfGas_VALUE = 211;
    /**
     * <pre>
     * ErrMemoTooLarge indicates that the transaction memo is too large
     * </pre>
     *
     * <code>ErrMemoTooLarge = 212;</code>
     */
    public static final int ErrMemoTooLarge_VALUE = 212;
    /**
     * <pre>
     * ErrInsufficientFee indicates that the gas fee is insufficient
     * </pre>
     *
     * <code>ErrInsufficientFee = 213;</code>
     */
    public static final int ErrInsufficientFee_VALUE = 213;
    /**
     * <pre>
     * ErrTooManySignatures indicates that the transaction has too many signatures
     * </pre>
     *
     * <code>ErrTooManySignatures = 214;</code>
     */
    public static final int ErrTooManySignatures_VALUE = 214;
    /**
     * <pre>
     * ErrNoSignatures indicates that the transaction has no signatures
     * </pre>
     *
     * <code>ErrNoSignatures = 215;</code>
     */
    public static final int ErrNoSignatures_VALUE = 215;
    /**
     * <pre>
     * ErrGasOverflow that an action results in a gas consumption unsigned integer overflow
     * </pre>
     *
     * <code>ErrGasOverflow = 216;</code>
     */
    public static final int ErrGasOverflow_VALUE = 216;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ErrCode valueOf(int value) {
      return forNumber(value);
    }

    public static ErrCode forNumber(int value) {
      switch (value) {
        case 0: return Undefined;
        case 1: return TODO;
        case 2: return ErrNotImplemented;
        case 3: return ErrInternal;
        case 100: return ErrInvalidInput;
        case 101: return ErrBridgeInterrupted;
        case 102: return ErrMissingInput;
        case 103: return ErrSerialization;
        case 104: return ErrDeserialization;
        case 105: return ErrInitService;
        case 150: return ErrCryptoKeyTypeUnknown;
        case 151: return ErrCryptoKeyNotFound;
        case 152: return ErrNoActiveAccount;
        case 153: return ErrRunGRPCServer;
        case 154: return ErrDecryptionFailed;
        case 200: return ErrTxDecode;
        case 201: return ErrInvalidSequence;
        case 202: return ErrUnauthorized;
        case 203: return ErrInsufficientFunds;
        case 204: return ErrUnknownRequest;
        case 205: return ErrInvalidAddress;
        case 206: return ErrUnknownAddress;
        case 207: return ErrInvalidPubKey;
        case 208: return ErrInsufficientCoins;
        case 209: return ErrInvalidCoins;
        case 210: return ErrInvalidGasWanted;
        case 211: return ErrOutOfGas;
        case 212: return ErrMemoTooLarge;
        case 213: return ErrInsufficientFee;
        case 214: return ErrTooManySignatures;
        case 215: return ErrNoSignatures;
        case 216: return ErrGasOverflow;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ErrCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ErrCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrCode>() {
            @java.lang.Override
            public ErrCode findValueByNumber(int number) {
              return ErrCode.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return ErrCodeVerifier.INSTANCE;
    }

    private static final class ErrCodeVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new ErrCodeVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return ErrCode.forNumber(number) != null;
            }
          };

    private final int value;

    private ErrCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:land.gno.gnomobile.v1.ErrCode)
  }

  public interface ErrDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:land.gno.gnomobile.v1.ErrDetails)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .land.gno.gnomobile.v1.ErrCode codes = 1 [json_name = "codes"];</code>
     * @return A list containing the codes.
     */
    java.util.List<land.gno.gnomobile.v1.Rpc.ErrCode> getCodesList();
    /**
     * <code>repeated .land.gno.gnomobile.v1.ErrCode codes = 1 [json_name = "codes"];</code>
     * @return The count of codes.
     */
    int getCodesCount();
    /**
     * <code>repeated .land.gno.gnomobile.v1.ErrCode codes = 1 [json_name = "codes"];</code>
     * @param index The index of the element to return.
     * @return The codes at the given index.
     */
    land.gno.gnomobile.v1.Rpc.ErrCode getCodes(int index);
    /**
     * <code>repeated .land.gno.gnomobile.v1.ErrCode codes = 1 [json_name = "codes"];</code>
     * @return A list containing the enum numeric values on the wire for codes.
     */
    java.util.List<java.lang.Integer>
    getCodesValueList();
    /**
     * <code>repeated .land.gno.gnomobile.v1.ErrCode codes = 1 [json_name = "codes"];</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of codes at the given index.
     */
    int getCodesValue(int index);
  }
  /**
   * Protobuf type {@code land.gno.gnomobile.v1.ErrDetails}
   */
  public  static final class ErrDetails extends
      com.google.protobuf.GeneratedMessageLite<
          ErrDetails, ErrDetails.Builder> implements
      // @@protoc_insertion_point(message_implements:land.gno.gnomobile.v1.ErrDetails)
      ErrDetailsOrBuilder {
    private ErrDetails() {
      codes_ = emptyIntList();
    }
    public static final int CODES_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.IntList codes_;
    private static final com.google.protobuf.Internal.ListAdapter.Converter<
        java.lang.Integer, land.gno.gnomobile.v1.Rpc.ErrCode> codes_converter_ =
            new com.google.protobuf.Internal.ListAdapter.Converter<
                java.lang.Integer, land.gno.gnomobile.v1.Rpc.ErrCode>() {
              @java.lang.Override
              public land.gno.gnomobile.v1.Rpc.ErrCode convert(java.lang.Integer from) {
                land.gno.gnomobile.v1.Rpc.ErrCode result = land.gno.gnomobile.v1.Rpc.ErrCode.forNumber(from);
                return result == null ? land.gno.gnomobile.v1.Rpc.ErrCode.UNRECOGNIZED : result;
              }
            };
    /**
     * <code>repeated .land.gno.gnomobile.v1.ErrCode codes = 1 [json_name = "codes"];</code>
     * @return A list containing the codes.
     */
    @java.lang.Override
    public java.util.List<land.gno.gnomobile.v1.Rpc.ErrCode> getCodesList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, land.gno.gnomobile.v1.Rpc.ErrCode>(codes_, codes_converter_);
    }
    /**
     * <code>repeated .land.gno.gnomobile.v1.ErrCode codes = 1 [json_name = "codes"];</code>
     * @return The count of codes.
     */
    @java.lang.Override
    public int getCodesCount() {
      return codes_.size();
    }
    /**
     * <code>repeated .land.gno.gnomobile.v1.ErrCode codes = 1 [json_name = "codes"];</code>
     * @param index The index of the element to return.
     * @return The codes at the given index.
     */
    @java.lang.Override
    public land.gno.gnomobile.v1.Rpc.ErrCode getCodes(int index) {
      land.gno.gnomobile.v1.Rpc.ErrCode result = land.gno.gnomobile.v1.Rpc.ErrCode.forNumber(codes_.getInt(index));
      return result == null ? land.gno.gnomobile.v1.Rpc.ErrCode.UNRECOGNIZED : result;
    }
    /**
     * <code>repeated .land.gno.gnomobile.v1.ErrCode codes = 1 [json_name = "codes"];</code>
     * @return A list containing the enum numeric values on the wire for codes.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
    getCodesValueList() {
      return codes_;
    }
    /**
     * <code>repeated .land.gno.gnomobile.v1.ErrCode codes = 1 [json_name = "codes"];</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of codes at the given index.
     */
    @java.lang.Override
    public int getCodesValue(int index) {
      return codes_.getInt(index);
    }
    private int codesMemoizedSerializedSize;
    private void ensureCodesIsMutable() {
      com.google.protobuf.Internal.IntList tmp = codes_;
      if (!tmp.isModifiable()) {
        codes_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
      }
    }
    /**
     * <code>repeated .land.gno.gnomobile.v1.ErrCode codes = 1 [json_name = "codes"];</code>
     * @param index The index to set the value at.
     * @param value The codes to set.
     */
    private void setCodes(
        int index, land.gno.gnomobile.v1.Rpc.ErrCode value) {
      value.getClass();
  ensureCodesIsMutable();
      codes_.setInt(index, value.getNumber());
    }
    /**
     * <code>repeated .land.gno.gnomobile.v1.ErrCode codes = 1 [json_name = "codes"];</code>
     * @param value The codes to add.
     */
    private void addCodes(land.gno.gnomobile.v1.Rpc.ErrCode value) {
      value.getClass();
  ensureCodesIsMutable();
      codes_.addInt(value.getNumber());
    }
    /**
     * <code>repeated .land.gno.gnomobile.v1.ErrCode codes = 1 [json_name = "codes"];</code>
     * @param values The codes to add.
     */
    private void addAllCodes(
        java.lang.Iterable<? extends land.gno.gnomobile.v1.Rpc.ErrCode> values) {
      ensureCodesIsMutable();
      for (land.gno.gnomobile.v1.Rpc.ErrCode value : values) {
        codes_.addInt(value.getNumber());
      }
    }
    /**
     * <code>repeated .land.gno.gnomobile.v1.ErrCode codes = 1 [json_name = "codes"];</code>
     */
    private void clearCodes() {
      codes_ = emptyIntList();
    }
    /**
     * <code>repeated .land.gno.gnomobile.v1.ErrCode codes = 1 [json_name = "codes"];</code>
     * @param value The enum numeric value on the wire for codes to set.
     */
    private void setCodesValue(
        int index, int value) {
      ensureCodesIsMutable();
      codes_.setInt(index, value);
    }
    /**
     * <code>repeated .land.gno.gnomobile.v1.ErrCode codes = 1 [json_name = "codes"];</code>
     * @param value The enum numeric value on the wire for codes to add.
     */
    private void addCodesValue(int value) {
      ensureCodesIsMutable();
      codes_.addInt(value);
    }
    /**
     * <code>repeated .land.gno.gnomobile.v1.ErrCode codes = 1 [json_name = "codes"];</code>
     * @param values The enum numeric values on the wire for codes to add.
     */
    private void addAllCodesValue(
        java.lang.Iterable<java.lang.Integer> values) {
      ensureCodesIsMutable();
      for (int value : values) {
        codes_.addInt(value);
      }
    }

    public static land.gno.gnomobile.v1.Rpc.ErrDetails parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static land.gno.gnomobile.v1.Rpc.ErrDetails parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static land.gno.gnomobile.v1.Rpc.ErrDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static land.gno.gnomobile.v1.Rpc.ErrDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static land.gno.gnomobile.v1.Rpc.ErrDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static land.gno.gnomobile.v1.Rpc.ErrDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static land.gno.gnomobile.v1.Rpc.ErrDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static land.gno.gnomobile.v1.Rpc.ErrDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static land.gno.gnomobile.v1.Rpc.ErrDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static land.gno.gnomobile.v1.Rpc.ErrDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static land.gno.gnomobile.v1.Rpc.ErrDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static land.gno.gnomobile.v1.Rpc.ErrDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(land.gno.gnomobile.v1.Rpc.ErrDetails prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code land.gno.gnomobile.v1.ErrDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          land.gno.gnomobile.v1.Rpc.ErrDetails, Builder> implements
        // @@protoc_insertion_point(builder_implements:land.gno.gnomobile.v1.ErrDetails)
        land.gno.gnomobile.v1.Rpc.ErrDetailsOrBuilder {
      // Construct using land.gno.gnomobile.v1.Rpc.ErrDetails.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .land.gno.gnomobile.v1.ErrCode codes = 1 [json_name = "codes"];</code>
       * @return A list containing the codes.
       */
      @java.lang.Override
      public java.util.List<land.gno.gnomobile.v1.Rpc.ErrCode> getCodesList() {
        return instance.getCodesList();
      }
      /**
       * <code>repeated .land.gno.gnomobile.v1.ErrCode codes = 1 [json_name = "codes"];</code>
       * @return The count of codes.
       */
      @java.lang.Override
      public int getCodesCount() {
        return instance.getCodesCount();
      }
      /**
       * <code>repeated .land.gno.gnomobile.v1.ErrCode codes = 1 [json_name = "codes"];</code>
       * @param index The index of the element to return.
       * @return The codes at the given index.
       */
      @java.lang.Override
      public land.gno.gnomobile.v1.Rpc.ErrCode getCodes(int index) {
        return instance.getCodes(index);
      }
      /**
       * <code>repeated .land.gno.gnomobile.v1.ErrCode codes = 1 [json_name = "codes"];</code>
       * @param index The index to set the value at.
       * @param value The codes to set.
       * @return This builder for chaining.
       */
      public Builder setCodes(
          int index, land.gno.gnomobile.v1.Rpc.ErrCode value) {
        copyOnWrite();
        instance.setCodes(index, value);
        return this;
      }
      /**
       * <code>repeated .land.gno.gnomobile.v1.ErrCode codes = 1 [json_name = "codes"];</code>
       * @param value The codes to add.
       * @return This builder for chaining.
       */
      public Builder addCodes(land.gno.gnomobile.v1.Rpc.ErrCode value) {
        copyOnWrite();
        instance.addCodes(value);
        return this;
      }
      /**
       * <code>repeated .land.gno.gnomobile.v1.ErrCode codes = 1 [json_name = "codes"];</code>
       * @param values The codes to add.
       * @return This builder for chaining.
       */
      public Builder addAllCodes(
          java.lang.Iterable<? extends land.gno.gnomobile.v1.Rpc.ErrCode> values) {
        copyOnWrite();
        instance.addAllCodes(values);  return this;
      }
      /**
       * <code>repeated .land.gno.gnomobile.v1.ErrCode codes = 1 [json_name = "codes"];</code>
       * @return This builder for chaining.
       */
      public Builder clearCodes() {
        copyOnWrite();
        instance.clearCodes();
        return this;
      }
      /**
       * <code>repeated .land.gno.gnomobile.v1.ErrCode codes = 1 [json_name = "codes"];</code>
       * @return A list containing the enum numeric values on the wire for codes.
       */
      @java.lang.Override
      public java.util.List<java.lang.Integer>
      getCodesValueList() {
        return java.util.Collections.unmodifiableList(
            instance.getCodesValueList());
      }
      /**
       * <code>repeated .land.gno.gnomobile.v1.ErrCode codes = 1 [json_name = "codes"];</code>
       * @param index The index of the value to return.
       * @return The enum numeric value on the wire of codes at the given index.
       */
      @java.lang.Override
      public int getCodesValue(int index) {
        return instance.getCodesValue(index);
      }
      /**
       * <code>repeated .land.gno.gnomobile.v1.ErrCode codes = 1 [json_name = "codes"];</code>
       * @param index The index to set the value at.
       * @param value The enum numeric value on the wire for codes to set.
       * @return This builder for chaining.
       */
      public Builder setCodesValue(
          int index, int value) {
        copyOnWrite();
        instance.setCodesValue(index, value);
        return this;
      }
      /**
       * <code>repeated .land.gno.gnomobile.v1.ErrCode codes = 1 [json_name = "codes"];</code>
       * @param value The enum numeric value on the wire for codes to add.
       * @return This builder for chaining.
       */
      public Builder addCodesValue(int value) {
        copyOnWrite();
        instance.addCodesValue(value);
        return this;
      }
      /**
       * <code>repeated .land.gno.gnomobile.v1.ErrCode codes = 1 [json_name = "codes"];</code>
       * @param values The enum numeric values on the wire for codes to add.
       * @return This builder for chaining.
       */
      public Builder addAllCodesValue(
          java.lang.Iterable<java.lang.Integer> values) {
        copyOnWrite();
        instance.addAllCodesValue(values);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:land.gno.gnomobile.v1.ErrDetails)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new land.gno.gnomobile.v1.Rpc.ErrDetails();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "codes_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001,";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<land.gno.gnomobile.v1.Rpc.ErrDetails> parser = PARSER;
          if (parser == null) {
            synchronized (land.gno.gnomobile.v1.Rpc.ErrDetails.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<land.gno.gnomobile.v1.Rpc.ErrDetails>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:land.gno.gnomobile.v1.ErrDetails)
    private static final land.gno.gnomobile.v1.Rpc.ErrDetails DEFAULT_INSTANCE;
    static {
      ErrDetails defaultInstance = new ErrDetails();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ErrDetails.class, defaultInstance);
    }

    public static land.gno.gnomobile.v1.Rpc.ErrDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ErrDetails> PARSER;

    public static com.google.protobuf.Parser<ErrDetails> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
